name: "Tests"
on: [push, pull_request]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v1
        
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master

      - name: Test
        run: pwd && bash unit_test.sh
