name: "Tests"
on: [push, pull_request]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install xmllint and xmlstarlet
        run: sudo apt-get install -y libxml2-utils xmlstarlet
      - name: Test
        run: pwd && bash unit_test.sh
