name: "Tests"
on: [push, pull_request]
jobs:
  build:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils 
      - name: Install xmlstarlet
        run: sudo snap install xmlstarlet
      - name: Install highlight
        run: sudo apt install highlight
      - name: Run unit test
        run: bash unit_test.sh 2>&1 
